version: "3"
services:
  mongodb:
    image: mongo:3.4
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: --smallfiles
  app:
    environment:
       - JAVA_OPTS=-Dspring.data.mongodb.host=mongodb
    image: productapp
    ports:
    - 9090:8080
    links:
    - mongodb